### ISSUE TITLE
where is your EFI  files?  

### ISSUE THREAD

**Issue by ShiningXu** [a31user/-LG-15Z980-Monterey-EFI#1]

**Comment by a31user** [comment]
Thanks for my First Issue.
My EFI files are on the https://github.com/a31user/LG-15Z980-Monterey-EFI/releases page.
Attached as EFI.7z.

I think this EFI can support all the Z980 devices with kaby lake CPU.
And, careful for changing EFI smbios, you should change it to another MacBookPro15,2 or change the smbios and the model name in the usb mapping kext.

-Thanks, written by an Elementary School Developer In Korea-

谢谢你的第一期。
我的 EFI 文件位于 https://github.com/a31user/LG-15Z980-Monterey-EFI/releases 页面上。
作为 EFI.7z。

我认为这个 EFI 可以支持所有带有 kaby lake CPU 的 Z980 设备。
而且，在更改EFI smbios时，您应该小心将其更改为另一台MacBookPro15，2或更改usb映射kext中的smbios和型号名称。

-谢谢，由韩国的一位小学开发商撰写-
