### ISSUE TITLE
HDMI output with pink hue

### ISSUE THREAD

**Issue by sphades** [a31user/-LG-15Z980-Monterey-EFI#2]
Ran into an issue with the HDMI output displaying a pink hue. Also, video output is limited to 60hz on 1080p. (Dont have other monitors to try) Previously was 1080p/120hz on Catalina.

**Comment by a31user** [comment]
Oh! Sorry For Late Reply. I had known this problem few days ago and fixed it in my new EFI. I would upload my new EFI soon. Thanks.

**Comment by a31user** [comment]
I have released my new EFI. Please test it.

**Comment by sphades** [comment]
I tested the new EFI and it resolved this issue!
