### ISSUE TITLE
Wifi unable to connect to 5Ghz Wi-Fi networks

### ISSUE THREAD

**Issue by sphades** [a31user/-LG-15Z980-Monterey-EFI#3]
Unable to connect to any 5GHZ wifi networks. Unable to connect to iOS hotspots as well.

**Comment by a31user** [comment]
Sorry for late reply. I think it is a Airportitlwm Problem. Please test it in a new version of Airportitlwm, and try it. Or if it doesn't work, please wait for me to upload my new EFI, and test it please.

**Comment by a31user** [comment]
Thanks for reporting a problem, I have released my new EFI, please test it.
I have tested myself, 5ghz wifi works in my computer, but I couldn't test hotspot because I don't have an LTE APPLE DEVICE.
Thanks.

**Comment by sphades** [comment]
tested the new EFI, stil unable to connect to 5ghz networks or iPhone wireless hotspots.

**Comment by sphades** [comment]
I did more testing and found a few things.
Hotspot is a known limitation of `airportitlwm`, described [here](https://openintelwireless.github.io/itlwm/FAQ.html#installation).
As for the 5ghz issue, it turns out that once i change the authentication to WPA instead of WPA2, I am able to connect to 5Ghz networks.

**Comment by a31user** [comment]
Oh! I didn't knew that the hotspot was a limitation due to that I didn't use hotspot well. And the 5ghz problem seems like WPA problem because that my one also uses 5ghz WPA2 and works well.
